# Generated by Django 5.2.13 on 2026-05-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_groups_alter_empresa_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('descripcion_producto', models.TextField()),
                ('publico_objetivo', models.CharField(max_length=200)),
                ('tono', models.CharField(choices=[('profesional', 'Profesional'), ('divertido', 'Divertido'), ('urgente', 'Urgente'), ('emocional', 'Emocional'), ('motivacional', 'Motivacional')], default='profesional', max_length=20)),
                ('red_social', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='instagram', max_length=20)),
                ('foto_producto', models.ImageField(upload_to='campanas/productos/')),
                ('foto_modelo', models.ImageField(upload_to='campanas/modelos/')),
                ('imagen_generada', models.ImageField(blank=True, null=True, upload_to='campanas/generadas/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
